### ISSUE TITLE
Bulkdata with parquet results in stackoverflow

### ISSUE THREAD

**Issue by prb112** [LinuxForHealth/FHIR#2658]
**Describe the bug**

Bulkdata with parquet results in stackoverflow

```
org.slf4j.bridge.SLF4JBridgeHandler.callLocationAwareLogger(SLF4JBridgeHandler.java:221)
        at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:303)
        at java.logging/java.util.logging.Logger.log(Logger.java:979)
        at com.ibm.ws.logging.internal.WsLogger.log(WsLogger.java:138)
        at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
        at org.slf4j.impl.JDK14LoggerAdapter.info(JDK14LoggerAdapter.java:277)
        at org.apache.spark.internal.Logging.logInfo(Logging.scala:57)
        at org.apache.spark.internal.Logging.logInfo$(Logging.scala:56)
        at org.apache.spark.SparkContext.logInfo(SparkContext.scala:82)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:193)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2672)
        at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:945)
        at org.apache.spark.sql.SparkSession$Builder$$Lambda$597/0x00000000844b4560.apply(Unknown Source)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:939)
        at com.ibm.fhir.bulkdata.jbatch.export.system.ExportJobListener.beforeJob(ExportJobListener.java:78)
        at com.ibm.jbatch.container.artifact.proxy.JobListenerProxy.beforeJob(JobListenerProxy.java:43)
        at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.jobListenersBeforeJob(WorkUnitThreadControllerImpl.java:439)
        at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.startWorkUnitIfNotStopping(WorkUnitThreadControllerImpl.java:151)
        at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:170)
        at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
        at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
        at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
        at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:836)
```

**Environment**
Which version of IBM FHIR Server?
4.7.1

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by prb112** [comment]
take the slf4j out of the userlib and you shouldnt hit the issue

**Comment by lmsurpre** [comment]
> take the slf4j out of the userlib and you shouldnt hit the issue

I removed the `slf4j-nop-1.7.32.jar` jar from the userlib and that led to:
```
INFO Completed request[3.075 secs]: tenantId:[default] dsId:[default] user:[fhiruser] method:[POST] uri:[https://cluster1-573846-250babbbe4c3000e15508cd07c1d282b-0000.us-east.containers.appdomain.cloud/fhir-server/api/v4/$export] originalUri:[https://cluster1-573846-250babbbe4c3000e15508cd07c1d282b-0000.us-east.containers.appdomain.cloud/basic/$export] status:[202]
SystemErr SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SystemErr SLF4J: Defaulting to no-operation (NOP) logger implementation
SystemErr SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING WARNING: An illegal reflective access operation has occurred
WARNING WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/ol/wlp/usr/servers/defaultServer/userlib/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING WARNING: All illegal access operations will be denied in a future release
INFO FFDC1015I: An FFDC Incident has been created: "java.lang.NoClassDefFoundError: org.slf4j.impl.StaticLoggerBinder com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl 181" at ffdc_21.08.29_21.56.08.0.log
```

Here's what I think is going on:
The original error messages mentioned at https://github.com/IBM/FHIR/issues/2658#issuecomment-907495107 was actually being throw by our fhir-server-webapp because userlib is on the classpath there while we already have an slf4j binding (slf4j-jdk14).
Removing the nop binding from userlib fixed that but then led to this new issue because fhir-bulkdata-webapp doesn't have any other binding.
I tested a fix which is to exclude the nop binding from the script I'm using to gather parquet dep jars for userlib AND ALSO include the `slf4j-jdk14` binding in fhir-bulkdata-webapp war.

**Comment by lmsurpre** [comment]
I opened https://github.com/IBM/FHIR/pull/2729 with this proposed fix.
