### ISSUE TITLE
Generated JSON parser barfs on null value that should be an object

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3090]
**Describe the bug**
While investigating the examples for R4B I hit a few cases where the JSONParser is throwing a ClassCastException

```
Dec 07, 2021 8:25:22 AM com.ibm.fhir.model.spec.test.R4ExamplesDriver processExample
SEVERE: readResource(json/spec/ingredient-example.json) unexpected failure: class jakarta.json.JsonValueImpl cannot be cast to class jakarta.json.JsonObject (jakarta.json.JsonValueImpl and jakarta.json.JsonObject are in unnamed module of loader 'app') [Ingredient.substance], Ingredient.substance
Exception in thread "main" json/spec/ingredient-example.json: wanted:         OK got:      PARSE
        at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:289)
        at com.ibm.fhir.model.spec.test.R4ExamplesTest.main(R4ExamplesTest.java:55)
Caused by: com.ibm.fhir.model.parser.exception.FHIRParserException: class jakarta.json.JsonValueImpl cannot be cast to class jakarta.json.JsonObject (jakarta.json.JsonValueImpl and jakarta.json.JsonObject are in unnamed module of loader 'app') [Ingredient.substance]  [probeId=7f-0-0-1-c07d0c95-c154-49a2-92e6-9c02a47173c9]
        at com.ibm.fhir.model.parser.FHIRJsonParser.parseAndFilter(FHIRJsonParser.java:160)
        at com.ibm.fhir.model.parser.FHIRJsonParser.parseAndFilter(FHIRJsonParser.java:112)
        at com.ibm.fhir.model.parser.FHIRJsonParser.parse(FHIRJsonParser.java:92)
        at com.ibm.fhir.model.spec.test.R4ExamplesDriver.readResource(R4ExamplesDriver.java:441)
        at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:254)
        ... 1 more
Caused by: java.lang.ClassCastException: class jakarta.json.JsonValueImpl cannot be cast to class jakarta.json.JsonObject (jakarta.json.JsonValueImpl and jakarta.json.JsonObject are in unnamed module of loader 'app')
        at org.eclipse.parsson.JsonArrayBuilderImpl$JsonArrayImpl.getJsonObject(JsonArrayBuilderImpl.java:377)
        at com.ibm.fhir.model.parser.FHIRJsonParser.parseIngredientSubstance(FHIRJsonParser.java:12933)
        at com.ibm.fhir.model.parser.FHIRJsonParser.parseIngredient(FHIRJsonParser.java:12896)
        at com.ibm.fhir.model.parser.FHIRJsonParser.parseResource(FHIRJsonParser.java:313)
        at com.ibm.fhir.model.parser.FHIRJsonParser.parseAndFilter(FHIRJsonParser.java:158)
        ... 5 more
```

The issue here is that the data has a repeating BackboneElement and the instance has a null value in that list.
This is incorrect according to https://hl7.org/fhir/r4/json.html
> Just as in XML, JSON objects and arrays are never empty, and properties never have null values (except for a special case documented below). Omit a property if it is empty

However, I think our parser should still be more resilient to this bad input.

**Environment**
Which version of IBM FHIR Server?

**To Reproduce**
1. Parse an example where there is a repeating backbone element and that element has an explicitly null value.
Example:
```
{
  "resourceType": "Ingredient",
  "id": "example",
  "text": {
    "status": "generated",
    "div": "\u003cdiv xmlns\u003d\"http://www.w3.org/1999/xhtml\"\u003e\u003cp\u003e\u003cb\u003eGenerated Narrative\u003c/b\u003e\u003c/p\u003e\u003cdiv\u003e\u003cp\u003eResource \u0026quot;example\u0026quot; \u003c/p\u003e\u003c/div\u003e\u003cp\u003e\u003cb\u003estatus\u003c/b\u003e: active\u003c/p\u003e\u003cp\u003e\u003cb\u003erole\u003c/b\u003e: ActiveBase \u003cspan\u003e (ingredientRole#ActiveBase)\u003c/span\u003e\u003c/p\u003e\u003ch3\u003eManufacturers\u003c/h3\u003e\u003ctable\u003e\u003ctr\u003e\u003ctd\u003e-\u003c/td\u003e\u003ctd\u003e\u003cb\u003eManufacturer\u003c/b\u003e\u003c/td\u003e\u003c/tr\u003e\u003ctr\u003e\u003ctd\u003e*\u003c/td\u003e\u003ctd\u003e\u003ca\u003eOrganization/example\u003c/a\u003e\u003c/td\u003e\u003c/tr\u003e\u003c/table\u003e\u003cblockquote\u003e\u003cp\u003e\u003cb\u003esubstance\u003c/b\u003e\u003c/p\u003e\u003c/blockquote\u003e\u003cp\u003e\u003cb\u003eException generating Narrative: Unknown type \u003c/b\u003e\u003c/p\u003e\u003c/div\u003e"
  },
  "status": "active",
  "role": {
    "coding": [
      {
        "system": "http://ema.europa.eu/example/ingredientRole",
        "code": "ActiveBase"
      }
    ]
  },
  "manufacturer": [
    {
      "manufacturer": {
        "reference": "Organization/example"
      }
    }
  ],
  "substance": {
    "strength": [
      null
    ]
  }
}
```

Note that this particular example (from https://build.fhir.org/branches/R4B/ingredient-example.json.html) is invalid in another way as well:  missing required `element Ingredient.substance.code`.

**Expected behavior**
Instead of an "ClassCastException" we should get back a reasonable error message that indicate the source data is incorrect (ideally with where / why type info).

**Additional context**

**Comment by lmsurpre** [comment]
I think I included a fix for this with the codegenerator changes for `r4b`...needs to get confirmed

**Comment by punktilious** [comment]
QA: Submitted the resource and got a 400 response:

```
{"resourceType":"OperationOutcome","issue":[{"severity":"fatal","code":"invalid","details":{"text":"FHIRProvider: Expected: OBJECT but found: NULL for element: strength [Ingredient.substance]"},"expression":["Ingredient.substance"]}]}rarnold:qa$ 
```
