### ISSUE TITLE
support memberOf check against new CodeableReference datatype

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3634]
**Is your feature request related to a problem? Please describe.**
In the current `r4b-rebased` branch, one of our ClinicalUseDefinition examples fails validation due to the following:
```
Caused by: java.lang.RuntimeException: An error occurred while validating constraint: clinicalUseDefinition-5 with location: indication.intendedEffect and expression: $this.memberOf('http://hl7.org/fhir/ValueSet/product-intended-use', 'preferred') at path: ClinicalUseDefinition
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:436)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:368)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:337)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.doVisit(FHIRValidator.java:297)
	at com.ibm.fhir.path.visitor.FHIRPathDefaultNodeVisitor.visit(FHIRPathDefaultNodeVisitor.java:81)
	at com.ibm.fhir.path.FHIRPathResourceNode.accept(FHIRPathResourceNode.java:197)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:269)
	at com.ibm.fhir.validation.FHIRValidator.validate(FHIRValidator.java:217)
	... 36 more
Caused by: com.ibm.fhir.path.exception.FHIRPathException: java.lang.IllegalArgumentException: The 'memberOf' function must be invoked on a coded element node, quantity element node, string element node, or uri element node  [probeId=7f-0-0-1-427f7dfa-6586-4683-a347-a9e1266e3bb0]
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator.evaluate(FHIRPathEvaluator.java:257)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:414)
	... 43 more
Caused by: java.lang.IllegalArgumentException: The 'memberOf' function must be invoked on a coded element node, quantity element node, string element node, or uri element node
	at com.ibm.fhir.path.function.MemberOfFunction.apply(MemberOfFunction.java:88)
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitFunction(FHIRPathEvaluator.java:1200)
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitFunction(FHIRPathEvaluator.java:1)
	at com.ibm.fhir.path.FHIRPathParser$FunctionContext.accept(FHIRPathParser.java:1140)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitFunctionInvocation(FHIRPathEvaluator.java:1124)
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitFunctionInvocation(FHIRPathEvaluator.java:1)
	at com.ibm.fhir.path.FHIRPathParser$FunctionInvocationContext.accept(FHIRPathParser.java:1051)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitInvocationExpression(FHIRPathEvaluator.java:863)
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitInvocationExpression(FHIRPathEvaluator.java:1)
	at com.ibm.fhir.path.FHIRPathParser$InvocationExpressionContext.accept(FHIRPathParser.java:279)
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.evaluate(FHIRPathEvaluator.java:302)
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator.evaluate(FHIRPathEvaluator.java:255)
	... 44 more
```

I think its because this `indication.intendedEffect` is of type "CodeableReference"

**Describe the solution you'd like**
Allow memberOf to execute against FHIR elements with this new data type.

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  validation should work against instances that use this new datatype like ClinicalUseDefinition

**Additional context**

**Comment by punktilious** [comment]
Check we can CREATE all the ClinicalUseDefinition resources in our examples:

```
for file in $(find /path/to/git/FHIR/fhir-examples -name 'ClinicalUseDefinition*.json'); do
    curl -k -i \
    -H 'Content-Type: application/json' \
    -X POST \
    -u 'fhiruser:change-password' 'https://localhost:9443/fhir-server/api/v4/ClinicalUseDefinition' \
    -d "@${file}"
done
```
Every example gets a 201 response.

**Comment by punktilious** [comment]
Note search parameters do not currently work for the CodeableReference datatype. See #3854
