### ISSUE TITLE
Support for Java 17

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3788]
**Is your feature request related to a problem? Please describe.**
While trying to start the fhir-server with OpenJDK 17 (Temurin), I see the following issue:
```
Exception = java.lang.reflect.InaccessibleObjectException
Source = com.ibm.ws.kernel.service.location.internal.Activator
probeid = 122
Stack Dump = java.lang.reflect.InaccessibleObjectException: Unable to make field private static javax.naming.spi.InitialContextFactoryBuilder javax.naming.spi.NamingManager.initctx_factory_builder accessible: module java.naming does not "opens javax.naming.spi" to unnamed module @62367338
    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
    at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
    at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
    at com.ibm.ws.kernel.service.location.internal.Activator.stop(Activator.java:114)
    at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:870)
    at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:862)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
    at org.eclipse.osgi.container.Module.doStop(Module.java:660)
    at org.eclipse.osgi.container.Module.stop(Module.java:521)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1888)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1763)
    at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
    at org.eclipse.osgi.container.Module.doStop(Module.java:660)
    at org.eclipse.osgi.container.Module.stop(Module.java:521)
    at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
    at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Describe the solution you'd like**
Make it possible to run the FHIR server with Java 17 (but keep Java 11 support as well).

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
If JAVA_HOME is not set, we hit this issue instead:  https://github.com/OpenLiberty/open-liberty/issues/19876

**Comment by lmsurpre** [comment]
Relates to (and may be fixed by) #3405

**Comment by lmsurpre** [comment]
Today I am unable to reproduce this issue.  Will need to keep an eye on it.  I won't consider the issue addressed until we've added java 17 to our test matrix.

**Comment by lmsurpre** [comment]
Potentially some modules-related / reflection-related issues, so increasing estimate.
