### ISSUE TITLE
Bulk operation transaction fails due to new MetricHandle imbalance

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#3911]
**Describe the bug**

[8/22/22, 21:45:29:291 UTC] 00000084 RegisteredSyn E   WTRN0074E: Exception caught from after_completion synchronization operation: java.lang.IllegalStateException: Metric being closed is '/M_JDBC_COMMIT/' but currentMetric is '/M_JDBC_COMMIT/M_JDBC_COMMIT/M_JDBC_COMMIT/'
        at org.linuxforhealth.fhir.config.FHIRRequestContext.endMetric(FHIRRequestContext.java:364)
        at org.linuxforhealth.fhir.config.MetricHandle.close(MetricHandle.java:82)
        at org.linuxforhealth.fhir.persistence.jdbc.impl.CacheTransactionSync.afterCompletion(CacheTransactionSync.java:85)
        at com.ibm.tx.jta.impl.RegisteredSyncs.coreDistributeAfter(RegisteredSyncs.java:301)
        at com.ibm.tx.jta.impl.RegisteredSyncs.distributeAfter(RegisteredSyncs.java:278)
        at com.ibm.tx.jta.embeddable.impl.EmbeddableTransactionImpl.distributeAfter(EmbeddableTransactionImpl.java:315)
        at com.ibm.tx.jta.impl.TransactionImpl.postCompletion(TransactionImpl.java:2484)
        at com.ibm.tx.jta.impl.TransactionImpl.internalCommit(TransactionImpl.java:1541)
        at com.ibm.tx.jta.impl.TransactionImpl.coreStage2CommitProcessing(TransactionImpl.java:875)
        at com.ibm.tx.jta.impl.TransactionImpl.stage2CommitProcessing(TransactionImpl.java:912)
        at com.ibm.tx.jta.impl.TransactionImpl.processCommit(TransactionImpl.java:773)
        at com.ibm.tx.jta.impl.TransactionImpl.commit(TransactionImpl.java:713)
        at com.ibm.tx.jta.impl.TranManagerImpl.commit(TranManagerImpl.java:153)
        at com.ibm.tx.jta.impl.TranManagerSet.commit(TranManagerSet.java:110)
        at com.ibm.tx.jta.impl.UserTransactionImpl.commit(UserTransactionImpl.java:145)
        at com.ibm.tx.jta.embeddable.impl.EmbeddableUserTransactionImpl.commit(EmbeddableUserTransactionImpl.java:101)
        at com.ibm.ws.transaction.services.UserTransactionService.commit(UserTransactionService.java:72)
        at com.ibm.jbatch.container.transaction.impl.JTAUserTransactionAdapter.commit(JTAUserTransactionAdapter.java:101)
... 

It appears as though transaction data is being registered multiple times but the after commit is called only once or possibly in a different order. This appears to be down to this logic in FHIRUserTransactionAdapter:

```
        FHIRRequestContext ctx = FHIRRequestContext.get();
        boolean bulk = ctx != null && ctx.isBulk();
        ...
        } else if (isActive(status) && bulk) {
            // On starting a bulk transaction, we need to register a callback so that
            // the cache is informed when the transaction commits it can promote thread-local
            // ids to the shared caches.
            syncRegistry.registerInterposedSynchronization(new CacheTransactionSync(this.syncRegistry, this.cache, this.transactionDataKey, this.afterTransactionHandler));

            // transaction is already active, so this is a nested request
            this.startCount++;
```

**Environment**
Which version of IBM FHIR Server? 5.0.0-RC1

**To Reproduce**
See errors in e2e integration tests related to bulk export/import.

**Expected behavior**
The transaction should commit successfully without this error.

**Additional context**
The transaction is initiated by the JavaBatch framework. The transaction sync data should only be registered once, so the call needs to be guarded by a check to see if this instance is the first occurrence.

**Comment by lmsurpre** [comment]
I downloaded the CI test results (both `minio` and `azurite`) from a recent run and searched for `java.lang.IllegalStateException`.  I found quite a few, but they were all unrelated to bulk export.

Interestingly, I found the `minio` tests had a failed export job:
```
[8/29/22, 11:39:43:097 UTC] com.ibm.ws.batch.JobLogger                                     CWWKY0013I: Partition 0 ended with batch status STOPPED and exit status STOPPED for step step1 for job instance 3 and job execution 3.
[8/29/22, 11:39:43:100 UTC] com.ibm.ws.batch.JobLogger                                     CWWKY0013I: Partition 1 ended with batch status FAILED and exit status FAILED for step step1 for job instance 3 and job execution 3.
[8/29/22, 11:39:43:101 UTC] com.ibm.ws.batch.JobLogger                                     CWWKY0019W: Step step1 failed with batch status FAILED and exit status null for job instance 3 and job execution 3.
[8/29/22, 11:39:43:154 UTC] com.ibm.ws.batch.JobLogger                                     CWWKY0030I: An exception occurred while running the step step1.
com.ibm.jbatch.container.exception.BatchContainerRuntimeException: One or more partitions failed: [For partitioned step: step1, the partition # 1 ended with status 'FAILED]
	at com.ibm.jbatch.container.controller.impl.PartitionedStepControllerImpl.checkFinishedPartitionsForFailures(PartitionedStepControllerImpl.java:1021)
	at com.ibm.jbatch.container.controller.impl.PartitionedStepControllerImpl.invokeCoreStep(PartitionedStepControllerImpl.java:475)
	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
	at com.ibm.jbatch.container.controller.impl.PartitionedStepControllerImpl.execute(PartitionedStepControllerImpl.java:201)
	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:871)
```

unfortunately, the corresponding part.1.log file had no information.

when I ran the same thing locally (`build/pre-integration-test-docker.sh minio` followed by running `ExportOperationTest` from fhir-server-test), it passed all the tests and I have no corresponding error.

**Comment by lmsurpre** [comment]
we have #3913 for further investigation into these tests and I think the problem described in this one is addressed.  closing.
