### ISSUE TITLE
Schema update required: whole-schema-version not supported

### ISSUE THREAD

**Issue by kidus-tiliksew** [LinuxForHealth/FHIR#4085]
**Describe the bug**

I get the following error in the logs after starting the server and hitting the healthcheck `curl -k -i -u 'fhiruser:change-password' 'https://localhost:9443/fhir-server/api/v4/$healthcheck'`

```
[11/17/22, 14:02:35:889 UTC] 0000002e linuxforhealth.fhir.server.filter.rest.FHIRRestServletFilter I Received request: tenantId:[default] dsId:[default] user:[fhiruser] method:[GET] uri:[https://localhost:9443/fhir-server/api/v4/$healthcheck]
[11/17/22, 14:02:36:346 UTC] 0000002e health.fhir.server.interceptor.FHIRPersistenceInterceptorMgr I Loaded the following persistence interceptors: []
[11/17/22, 14:02:36:363 UTC] 0000002e com.ibm.ws.recoverylog.spi.RecoveryDirectorImpl              I CWRLS0010I: Performing recovery processing for local WebSphere server (defaultServer).
[11/17/22, 14:02:36:403 UTC] 0000002e com.ibm.ws.recoverylog.spi.RecoveryDirectorImpl              I CWRLS0012I: All persistent services have been directed to perform recovery processing for this WebSphere server (defaultServer).
[11/17/22, 14:02:36:403 UTC] 0000005f com.ibm.tx.jta.impl.RecoveryManager                          I WTRN0135I: Transaction service recovering no transactions.
[11/17/22, 14:02:36:427 UTC] 0000002e com.ibm.ws.jca.cm.ConnectorService                           I J2CA8050I: An authentication alias should be used instead of defining a user name and password on dataSource[fhirDefaultDefault].
[11/17/22, 14:02:38:536 UTC] 0000002e com.ibm.ws.rsadapter.impl.DatabaseHelper                     I DSRA8203I: Database product name : PostgreSQL
[11/17/22, 14:02:38:578 UTC] 0000002e com.ibm.ws.rsadapter.impl.DatabaseHelper                     I DSRA8204I: Database product version : 15.1 (Debian 15.1-1.pgdg110+1)
[11/17/22, 14:02:38:580 UTC] 0000002e com.ibm.ws.rsadapter.impl.DatabaseHelper                     I DSRA8205I: JDBC driver name  : PostgreSQL JDBC Driver
[11/17/22, 14:02:38:580 UTC] 0000002e com.ibm.ws.rsadapter.impl.DatabaseHelper                     I DSRA8206I: JDBC driver version  : 42.5.0
[11/17/22, 14:02:39:605 UTC] 0000002e forhealth.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl E Schema update required: whole-schema-version not supported
[11/17/22, 14:02:39:642 UTC] 0000002e nuxforhealth.fhir.persistence.jdbc.impl.CacheTransactionSync I Transaction failed - afterCompletion(status = STATUS_ROLLEDBACK)
[11/17/22, 14:02:39:645 UTC] 0000002e org.linuxforhealth.fhir.server.resources.FHIRResource        E The persistence layer reported one or more issues
org.linuxforhealth.fhir.exception.FHIROperationException: The persistence layer reported one or more issues  [probeId=a-1-1-64-120b022d-45c6-4f4d-9919-7b601db65d52]
	at org.linuxforhealth.fhir.operation.healthcheck.HealthcheckOperation.checkOperationOutcome(HealthcheckOperation.java:86)
	at org.linuxforhealth.fhir.operation.healthcheck.HealthcheckOperation.doInvoke(HealthcheckOperation.java:59)
	at org.linuxforhealth.fhir.server.spi.operation.AbstractOperation.invoke(AbstractOperation.java:57)
	at org.linuxforhealth.fhir.server.util.FHIRRestHelper.doInvoke(FHIRRestHelper.java:1496)
	at org.linuxforhealth.fhir.server.resources.Operation.invoke(Operation.java:84)
	at org.linuxforhealth.fhir.server.resources.Operation$Proxy$_$$_WeldClientProxy.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:350)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:641)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:101)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:213)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:444)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:112)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:123)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:277)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:137)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doGet(IBMRestServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:193)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:98)
	at org.linuxforhealth.fhir.server.filter.rest.FHIRRestServletFilter.doFilter(FHIRRestServletFilter.java:177)
	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
	at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5058)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:316)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1239)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:468)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:427)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
	at com.ibm.ws.http.channel.h2internal.H2StreamProcessor$Http2Ready.run(H2StreamProcessor.java:1789)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[11/17/22, 14:02:39:690 UTC] 0000002e org.linuxforhealth.fhir.audit.AuditLogServiceFactory         I Successfully initialized audit log service: org.linuxforhealth.fhir.audit.impl.NopService
[11/17/22, 14:02:39:856 UTC] 0000002e linuxforhealth.fhir.server.filter.rest.FHIRRestServletFilter I Completed request[3.938073791 secs]: tenantId:[default] dsId:[default] user:[fhiruser] method:[GET] uri:[https://localhost:9443/fhir-server/api/v4/$healthcheck] status:[500]
```

**Environment**
Which version of LinuxForHealth FHIR Server?

Installed `fhir-install-5.1.0`

**To Reproduce**

1. Configure the default datasource in `configDropins` to the following
```
<server>
    <!-- ============================================================== -->
    <!-- This datasource aligns with the Apache Derby database that is  -->
    <!-- created by the linuxforhealth/fhir-server BOOTSTRAP_DB process.-->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- TENANT: default; DSID: default; TYPE: read-write               -->
    <!-- ============================================================== -->
    <dataSource id="fhirDefaultDefault" jndiName="jdbc/fhir_default_default" type="javax.sql.XADataSource" statementCacheSize="200" syncQueryTimeoutWithTransactionTimeout="true" validationTimeout="30s">
        <jdbcDriver javax.sql.XADataSource="org.postgresql.xa.PGXADataSource" libraryRef="sharedLibPostgres" />
        <properties.postgresql
            serverName="localhost"
            portNumber="5432"
            databaseName="fhirdb"
            user="postgres"
            password="password"
            currentSchema="fhirdata"
        />
        <connectionManager maxPoolSize="200" minPoolSize="20"
            connectionTimeout="60s" maxIdleTime="2m"
            numConnectionsPerThreadLocal="0" />
    </dataSource>
</server>
```
2. Configure `fhir-server-config.json` to the following

```
{
    "__comment": "FHIR Server configuration",
    "fhirServer": {
        "core": {
            "tenantIdHeaderName": "X-FHIR-TENANT-ID",
            "datastoreIdHeaderName": "X-FHIR-DSID",
            "originalRequestUriHeaderName": "X-FHIR-FORWARDED-URL",
            "checkReferenceTypes": true,
            "conditionalDeleteMaxNumber": 10,
            "__comment": "The CI changes this to true, and the false is intentional as we recommend for performance reasons.",
            "serverRegistryResourceProviderEnabled": false,
            "disabledOperations": ""
        },
        "security": {
            "cors": true,
            "basic": {
                "enabled": true
            },
            "certificates": {
                "enabled": true
            },
            "oauth": {
                "enabled": false,
                "regUrl": "https://<host>:9443/oauth2/endpoint/oauth2-provider/registration",
                "authUrl": "https://<host>:9443/oauth2/endpoint/oauth2-provider/authorize",
                "tokenUrl": "https://<host>:9443/oauth2/endpoint/oauth2-provider/token",
                "smart": {
                    "enabled": false,
                    "scopes": ["openid", "profile", "fhirUser", "launch/patient", "patient/*.*", "offline_access"],
                    "capabilities": [
                        "sso-openid-connect",
                        "launch-standalone",
                        "client-public",
                        "client-confidential-symmetric",
                        "permission-offline",
                        "context-standalone-patient",
                        "permission-patient"
                    ]
                }
            }
        },
        "audit": {
            "serviceClassName" : "org.linuxforhealth.fhir.audit.impl.NopService",
            "serviceProperties" : {
            }
        },
        "persistence": {
            "factoryClassname": "org.linuxforhealth.fhir.persistence.jdbc.FHIRPersistenceJDBCFactory",
            "common": {
                "__comment": "Configuration properties common to all persistence layer implementations",
                "updateCreateEnabled": true
            },
            "jdbc": {
                "__comment": "Configuration properties for the JDBC persistence implementation",
                "enableCodeSystemsCache": true,
                "enableParameterNamesCache": true,
                "enableResourceTypesCache": true
            },
            "datasources": {
                "default": {
                    "type": "postgresql",
                    "currentSchema": "fhirdata",
                    "searchOptimizerOptions": {
                        "from_collapse_limit": 12,
                        "join_collapse_limit": 12
                    }
                }
            }
        },
        "bulkdata": {
            "enabled": false
        },
        "operations": {
            "erase": {
                "enabled": true,
                "allowedRoles": [
                    "FHIROperationAdmin",
                    "FHIRUsers"
                ]
            }
        }
    }
}
```
3. Run the schema tool 
```
java -jar fhir-persistence-schema-5.1.0-cli.jar --db-type postgresql --prop-file fhirdb.properties --schema-name fhirdata --create-schemas
```
With the following properies 

```
db.host=localhost
db.port=5432
db.database=fhirdb
user=postgres
password=password
```

4. Start server

**Additional context**

- Lastest PostgreSQL DB running on Docker 
- Java version `OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)`
- Apple M1

**Comment by lmsurpre** [comment]
It actually takes two steps to deploy the schema:
1. create-schemas
2. update-schema

I think you just missed the second step.

Please read through https://github.com/LinuxForHealth/FHIR/tree/main/fhir-persistence-schema#tldr and let us know if you have further questions.
