### ISSUE TITLE
FHIR Server can't find tenants

### ISSUE THREAD

**Issue by renom** [LinuxForHealth/FHIR#4093]
**Describe the bug**
After upgrading fhir server to the latest version, it worked for a while, then I got permanent error:
```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "fatal",
            "code": "invalid",
            "details": {
                "text": "FHIRException: No configured tenants were found"
            }
        }
    ]
}
```
It occurs on any request and even if I drop db and redeploy schema (I use PostgreSQL).

**Environment**
Arch Linux & Docker

**Additional context**
```
[11/23/22, 9:26:53:954 UTC] 00000065 FHIRRestServl I   Received request: tenantId:[default] dsId:[default] user:[fhiruser] method:[GET] uri:[http://127.0.0.1:9080/fhir-server/api/v4/Patient]
[11/23/22, 9:26:53:955 UTC] 00000065 FHIRRestServl I   Error while setting request context or processing request
                                 org.linuxforhealth.fhir.exception.FHIRException: No configured tenants were found  [probeId=ac-15-0-3-59b78103-fe85-4ce7-8648-55eea4dd8b63]
        at org.linuxforhealth.fhir.server.filter.rest.FHIRRestServletFilter.fetchValidConfiguredTenantId(FHIRRestServletFilter.java:553)
        at org.linuxforhealth.fhir.server.filter.rest.FHIRRestServletFilter.doFilter(FHIRRestServletFilter.java:144)
        at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
        at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1011)
        at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
        at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:85)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1239)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:468)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:427)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:327)
        at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
        at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:514)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:584)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:968)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1057)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:840)

[11/23/22, 9:26:54:002 UTC] 00000065 FHIRRestServl I   Completed request[0.048888651 secs]: tenantId:[default] dsId:[default] user:[fhiruser] method:[GET] uri:[http://127.0.0.1:9080/fhir-server/api/v4/Patient] status:[400]
```

**Comment by renom** [comment]
It's fixed somehow (it started to work fine after a while, but I didn't do anything to make it work). So I close the issue.
